package com.code.wecode.core.mapper;

import com.code.wecode.core.model.CodeUser;

public interface CodeUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table codeuser
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table codeuser
     *
     * @mbg.generated
     */
    int insert(CodeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table codeuser
     *
     * @mbg.generated
     */
    int insertSelective(CodeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table codeuser
     *
     * @mbg.generated
     */
    CodeUser selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table codeuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CodeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table codeuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CodeUser record);
    /**
     * 验证用户名/邮箱是否存在
     * @param userName
     * @return
     */
    CodeUser selectByUnionKey(String userName);
}