package com.code.wecode.core.model;

public class CodeUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column codeuser.userId
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column codeuser.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column codeuser.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column codeuser.userEmail
     *
     * @mbg.generated
     */
    private String useremail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column codeuser.userId
     *
     * @return the value of codeuser.userId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column codeuser.userId
     *
     * @param userid the value for codeuser.userId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column codeuser.userName
     *
     * @return the value of codeuser.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column codeuser.userName
     *
     * @param username the value for codeuser.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column codeuser.password
     *
     * @return the value of codeuser.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column codeuser.password
     *
     * @param password the value for codeuser.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column codeuser.userEmail
     *
     * @return the value of codeuser.userEmail
     *
     * @mbg.generated
     */
    public String getUseremail() {
        return useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column codeuser.userEmail
     *
     * @param useremail the value for codeuser.userEmail
     *
     * @mbg.generated
     */
    public void setUseremail(String useremail) {
        this.useremail = useremail == null ? null : useremail.trim();
    }
}